### ISSUE TITLE
How can i show all the participants to video to only host 

### ISSUE THREAD

**Issue by Boopalan-M** [ttejas123/Video_Con#3]
want to show the participants video only to the host and the participants don't want to see others video how can i acheive that

Thanks in advance!!!

**Comment by ttejas123** [comment]
1. add all users id in array and this array must be visible to everyone (use socket for that)

2. Than first users is always a host.

3. Add if else code to check whether user is host or not .

3. Based on that change css.

**Comment by Boopalan-M** [comment]
can i get the sample code for that. Bcoz  i using ur same code  for that but i didn't get the output.

 Thanks in advancee

**Comment by ttejas123** [comment]
I am currently working on different project, After finishing this I will get back to video_conf again. Until that try to solve by your self.

**Comment by Boopalan-M** [comment]
okk  can i know when u will reastart this project.Because i tried that to show the participants video only to host and the participants don't want to see the other particpants video and the host video.But i can't  get.plz help me as soon as possible

Thanks in advance!!!

**Comment by ttejas123** [comment]
Ok I am currently at hospital, so it's depends on laptop if I get that and
if I able to work here, I will help you as soon as I can.
Just I want to know why do you want that? Are you doing any internship or
job.

**Comment by Boopalan-M** [comment]
Bro for intetnship purpose

Boopalan M

**Comment by ttejas123** [comment]
Actually I am also building this for internship, but after building that
project I actually understand worth of that project, and how much this
people (company which gave me that intership) actually care and pay me for
it, and that's why I left and close that project. And that's why I don't
want to start that again. But it's intership so you should try by user self
that's what it mean.

**Comment by Boopalan-M** [comment]
Can i get ur mailid

Boopalan M

**Comment by ttejas123** [comment]
I am not that professional 
Massage me here it's my insta:-
https://www.instagram.com/p/CHqNjLhFeUUiPmrGkACde_cFSsBU0GR1oGj4gg0/?igshid=6tii12usg2mz
